name: "Build all PDFs"
on:
  push:
jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-output: ["pdf-all", "pdf-next"]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - name: Build PDFs
        run: nix build .#${{ matrix.build-output }}
      - name: Copy PDFs
        run: cp result/*.pdf .
      - name: Output PDFs
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: ./*.pdf
          if-no-files-found: error
