name: "Build all PDFs"
on:
  push:
jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Build PDFs
        run: nix build .#pdfs
      - name: Copy PDFs
        run: cp result/*.pdf .
      - name: Output PDFs
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: ./*.pdf
          if-no-files-found: error
